# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 17:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='milestone',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 23, 17, 53, 34, 731744, tzinfo=utc)),
        ),
    ]
