# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20170916_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='profiles',
            field=models.ManyToManyField(related_name='_profile_profiles_+', to='interface.Profile'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='milestone',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 24, 8, 16, 41, 711852, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
