# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-17 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20170917_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='milestone',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 24, 8, 54, 2, 546092, tzinfo=utc)),
        ),
    ]
