# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_auto_20170917_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_company',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='milestone',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 24, 10, 56, 9, 186752, tzinfo=utc)),
        ),
    ]
